[manifest]
version = '1.0.0'
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "if G.play.cards[i].ability.effect == 'Stone Card' then"
position = 'before'
match_indent = true
payload = '''
if G.play.cards[i].base.suit == 'cere_Nothings' then
    local inside = false
    for j=1, #scoring_hand do
        if scoring_hand[j] == G.play.cards[i] then
            inside = true
        end
    end
    if not inside then table.insert(pures, G.play.cards[i]) end
end
'''